### ISSUE TITLE
Google Cloud error

### ISSUE THREAD

**Issue by arunadissanayake** [asterisk/aeap-speech-to-text#14]
How to configure gcloud for this project. 
I am getting folwoing error
GoogleProvider: Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information. - ending stream
/usr/src/aeap-speech-to-text/node_modules/google-gax/node_modules/google-auth-library/build/src/auth/googleauth.js:292
        throw new Error(exports.GoogleAuthExceptionMessages.NO_ADC_FOUND);
              ^

Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (/usr/src/aeap-speech-to-text/node_modules/google-gax/node_modules/google-auth-library/build/src/auth/googleauth.js:292:15)

**Comment by arunadissanayake** [comment]
how to configure environment variable

**Comment by arunadissanayake** [comment]
sorted with export

**Comment by erwiower2** [comment]
That's my solution:

1. Make sure, that your Google Credentials .json file is located in `/etc/asterisk/`

2. Type in terminal `nano /etc/systemd/system/asterisk-aeap-websocket.service`

3. Put this in `/etc/systemd/system/asterisk-aeap-websocket.service`
```
[Unit]
Description=Startet das AEAP Speech-to-Text Skript
After=network.target

[Service]
Environment=GOOGLE_APPLICATION_CREDENTIALS=/etc/asterisk/favorable-tree-XXX.json
ExecStart=/usr/bin/node /etc/asterisk/aeap-speech-to-text/index.js
WorkingDirectory=/etc/asterisk/aeap-speech-to-text
Restart=on-failure
User=asterisk
Group=asterisk

[Install]
WantedBy=multi-user.target
```

4. Type in terminal and press ENTER: 
```
systemctl daemon-reload && systemctl enable asterisk-aeap-websocket.service && systemctl start asterisk-aeap-websocket.service
```

5. Type in terminal `systemctl status asterisk-aeap-wevsocket.service` and you should see the following result (you can also see the recognized words here):
```
● asterisk-aeap-websocket.service - Startet das AEAP Speech-to-Text Skript
   Loaded: loaded (/etc/systemd/system/asterisk-aeap-websocket.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2025-02-01 00:01:26 CET; 2 days ago
    Tasks: 11 (limit: 2307)
   Memory: 66.0M
   CGroup: /system.slice/asterisk-aeap-websocket.service
           └─24249 /usr/bin/node /etc/asterisk/aeap-speech-to-text/index.js
Feb 03 14:05:41 debian node[24249]: message: {"request":"setup","version":"0.1.0","codecs":[{"name":"ulaw"}],"params":{},"id":"98cfz126-217k-6f5l-fh32-3g478o2378r9"}
Feb 03 14:05:44 debian node[24249]: GoogleProvider: result: {"text":"hello test test test","score":41}```
